/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	identityserver "github.com/moov-io/identity/pkg/server"
)

func main() {
	log.Printf("Server started")

	IdentitiesApiService := identityserver.NewIdentitiesApiService()
	IdentitiesApiController := identityserver.NewIdentitiesApiController(IdentitiesApiService)

	InternalApiService := identityserver.NewInternalApiService()
	InternalApiController := identityserver.NewInternalApiController(InternalApiService)

	InvitesApiService := identityserver.NewInvitesApiService()
	InvitesApiController := identityserver.NewInvitesApiController(InvitesApiService)

	router := identityserver.NewRouter(IdentitiesApiController, InternalApiController, InvitesApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
