/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"

	"github.com/go-kit/kit/log"
	"github.com/moov-io/identity/pkg/webkeys"
)

var logger log.Logger

/*
This is used to rotate the jwks by our systems. It will generate a RSA256 public and private key for used.
*/
func main() {
	js, err := webkeys.NewGenerateJwksService()
	if err != nil {
		fmt.Printf("Unable to generate JWKS service - %s\n", err.Error())
		return
	}

	s, _ := js.(*webkeys.GenerateJwksService)

	fmt.Printf("Writing out generated JWKS files into ./\n")
	s.Save("./configs/")
}
