/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/moov-io/identity/pkg/logging"
)

func Logger(log logging.Logger, inner http.Handler, name string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		inner.ServeHTTP(w, r)

		log.WithMap(map[string]string{
			"request_method": r.Method,
			"require_uri":    r.RequestURI,
			"route_name":     name,
			"response_time":  time.Since(start).String(),
		}).Info().Log(fmt.Sprintf("%s %s %s", r.Method, r.RequestURI, name))
	})
}
