/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/moov-io/identity/pkg/client"
	"github.com/moov-io/identity/pkg/logging"
)

type loginLogContext struct {
	login *client.Login
}

func NewLoginLogContext(login *client.Login) logging.LogContext {
	return &loginLogContext{login: login}
}

func (i *loginLogContext) LogContext() map[string]string {
	return map[string]string{
		"login_credential_id": i.login.CredentialID,
		"login_tenant_id":     i.login.TenantID,
	}
}
