/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/moov-io/identity/pkg/client"
	"github.com/moov-io/identity/pkg/logging"
)

type Login = client.Login

type loginLogContext struct {
	login *Login
}

func NewLoginLogContext(login *Login) logging.LogContext {
	return &loginLogContext{login: login}
}

func (i *loginLogContext) LogContext() map[string]string {
	return map[string]string{
		"login_provider":      i.login.Provider,
		"login_subject_trunc": i.login.SubjectID[0:5],
	}
}
