/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"time"
)

// Invite - Describes an invite that was sent to a user to join.
type Invite struct {

	// UUID v4
	InviteID string `json:"inviteID,omitempty"`

	// UUID v4
	TenantID string `json:"tenantID,omitempty"`

	// Email Address
	Email string `json:"email,omitempty"`

	// UUID v4
	InvitedBy string `json:"invitedBy,omitempty"`

	InvitedOn time.Time `json:"invitedOn,omitempty"`

	ExpiresOn time.Time `json:"expiresOn,omitempty"`

	// If this invite has been redeemed for a registration
	Redeemed bool `json:"redeemed,omitempty"`
}
