/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/moov-io/identity/pkg/client"
	"github.com/moov-io/identity/pkg/logging"
)

type credentialLogContext struct {
	credential *client.Credential
}

func NewCredentialLogContext(credential *client.Credential) logging.LogContext {
	return &credentialLogContext{credential: credential}
}

func (i *credentialLogContext) LogContext() map[string]string {
	return map[string]string{
		"credential_id": i.credential.CredentialID,
	}
}
