/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/moov-io/identity/pkg/client"
)

// UpdateIdentity - Properties of an Identity. These users will under-go KYC checks thus all the information
type UpdateIdentity = client.UpdateIdentity
