/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"net/http"
)


// IdentitiesApiRouter defines the required methods for binding the api requests to a responses for the IdentitiesApi
// The IdentitiesApiRouter implementation should parse necessary information from the http request, 
// pass the data to a IdentitiesApiServicer to perform the required actions, then write the service results to the http response.
type IdentitiesApiRouter interface { 
	IdentitiesGet(http.ResponseWriter, *http.Request)
	IdentitiesIdentityIDCredentialsGet(http.ResponseWriter, *http.Request)
	IdentitiesIdentityIDGet(http.ResponseWriter, *http.Request)
	IdentitiesIdentityIDPut(http.ResponseWriter, *http.Request)
}
// InternalApiRouter defines the required methods for binding the api requests to a responses for the InternalApi
// The InternalApiRouter implementation should parse necessary information from the http request, 
// pass the data to a InternalApiServicer to perform the required actions, then write the service results to the http response.
type InternalApiRouter interface { 
	LoginPost(http.ResponseWriter, *http.Request)
	RegisterPost(http.ResponseWriter, *http.Request)
}
// InvitesApiRouter defines the required methods for binding the api requests to a responses for the InvitesApi
// The InvitesApiRouter implementation should parse necessary information from the http request, 
// pass the data to a InvitesApiServicer to perform the required actions, then write the service results to the http response.
type InvitesApiRouter interface { 
	InvitesGet(http.ResponseWriter, *http.Request)
	InvitesInviteIDDelete(http.ResponseWriter, *http.Request)
	InvitesPost(http.ResponseWriter, *http.Request)
}


// IdentitiesApiServicer defines the api actions for the IdentitiesApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type IdentitiesApiServicer interface { 
	IdentitiesGet(string) (interface{}, error)
	IdentitiesIdentityIDCredentialsGet(string) (interface{}, error)
	IdentitiesIdentityIDGet(string) (interface{}, error)
	IdentitiesIdentityIDPut(string, Identity) (interface{}, error)
}


// InternalApiServicer defines the api actions for the InternalApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type InternalApiServicer interface { 
	LoginPost(Login) (interface{}, error)
	RegisterPost(Register) (interface{}, error)
}


// InvitesApiServicer defines the api actions for the InvitesApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type InvitesApiServicer interface { 
	InvitesGet(string) (interface{}, error)
	InvitesInviteIDDelete(string) (interface{}, error)
	InvitesPost(Invite) (interface{}, error)
}
