/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"errors"
)

// InvitesApiService is a service that implents the logic for the InvitesApiServicer
// This service should implement the business logic for every endpoint for the InvitesApi API. 
// Include any external packages or services that will be required by this service.
type InvitesApiService struct {
}

// NewInvitesApiService creates a default api service
func NewInvitesApiService() InvitesApiServicer {
	return &InvitesApiService{}
}

// DeleteInvite - Delete an invite that was sent and invalidate the token.
func (s *InvitesApiService) DeleteInvite(inviteID string) (interface{}, error) {
	// TODO - update DeleteInvite with the required logic for this service method.
	// Add api_invites_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DeleteInvite' not implemented")
}

// ListInvites - List outstanding invites
func (s *InvitesApiService) ListInvites(orgID string) (interface{}, error) {
	// TODO - update ListInvites with the required logic for this service method.
	// Add api_invites_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ListInvites' not implemented")
}

// SendInvite - Send an email invite to a new user
func (s *InvitesApiService) SendInvite(invite Invite) (interface{}, error) {
	// TODO - update SendInvite with the required logic for this service method.
	// Add api_invites_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'SendInvite' not implemented")
}
