/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"errors"
)

// IdentitiesApiService is a service that implents the logic for the IdentitiesApiServicer
// This service should implement the business logic for every endpoint for the IdentitiesApi API. 
// Include any external packages or services that will be required by this service.
type IdentitiesApiService struct {
}

// NewIdentitiesApiService creates a default api service
func NewIdentitiesApiService() IdentitiesApiServicer {
	return &IdentitiesApiService{}
}

// IdentitiesGet - List identities and associates userId
func (s *IdentitiesApiService) IdentitiesGet(orgID string) (interface{}, error) {
	// TODO - update IdentitiesGet with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'IdentitiesGet' not implemented")
}

// IdentitiesIdentityIDCredentialsGet - List the credentials this user has used.
func (s *IdentitiesApiService) IdentitiesIdentityIDCredentialsGet(identityID string) (interface{}, error) {
	// TODO - update IdentitiesIdentityIDCredentialsGet with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'IdentitiesIdentityIDCredentialsGet' not implemented")
}

// IdentitiesIdentityIDGet - List identities and associates userId
func (s *IdentitiesApiService) IdentitiesIdentityIDGet(identityID string) (interface{}, error) {
	// TODO - update IdentitiesIdentityIDGet with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'IdentitiesIdentityIDGet' not implemented")
}

// IdentitiesIdentityIDPut - Update a specific Identity
func (s *IdentitiesApiService) IdentitiesIdentityIDPut(identityID string, identity Identity) (interface{}, error) {
	// TODO - update IdentitiesIdentityIDPut with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'IdentitiesIdentityIDPut' not implemented")
}
