/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"errors"
)

// InvitesApiService is a service that implents the logic for the InvitesApiServicer
// This service should implement the business logic for every endpoint for the InvitesApi API. 
// Include any external packages or services that will be required by this service.
type InvitesApiService struct {
}

// NewInvitesApiService creates a default api service
func NewInvitesApiService() InvitesApiServicer {
	return &InvitesApiService{}
}

// InvitesGet - List outstanding invites
func (s *InvitesApiService) InvitesGet(orgID string) (interface{}, error) {
	// TODO - update InvitesGet with the required logic for this service method.
	// Add api_invites_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'InvitesGet' not implemented")
}

// InvitesInviteIDDelete - Delete an invite that was sent and invalidate the token.
func (s *InvitesApiService) InvitesInviteIDDelete(inviteID string) (interface{}, error) {
	// TODO - update InvitesInviteIDDelete with the required logic for this service method.
	// Add api_invites_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'InvitesInviteIDDelete' not implemented")
}

// InvitesPost - Send an email invite to a new user
func (s *InvitesApiService) InvitesPost(invite Invite) (interface{}, error) {
	// TODO - update InvitesPost with the required logic for this service method.
	// Add api_invites_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'InvitesPost' not implemented")
}
