/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A IdentitiesApiController binds http requests to an api service and writes the service results to the http response
type IdentitiesApiController struct {
	service IdentitiesApiServicer
}

// NewIdentitiesApiController creates a default api controller
func NewIdentitiesApiController(s IdentitiesApiServicer) Router {
	return &IdentitiesApiController{service: s}
}

// Routes returns all of the api route for the IdentitiesApiController
func (c *IdentitiesApiController) Routes() Routes {
	return Routes{
		{
			"DisableIdentity",
			strings.ToUpper("Delete"),
			"/identities/{identityID}",
			c.DisableIdentity,
		},
		{
			"GetIdentity",
			strings.ToUpper("Get"),
			"/identities/{identityID}",
			c.GetIdentity,
		},
		{
			"ListIdentities",
			strings.ToUpper("Get"),
			"/identities",
			c.ListIdentities,
		},
		{
			"UpdateIdentity",
			strings.ToUpper("Put"),
			"/identities/{identityID}",
			c.UpdateIdentity,
		},
	}
}

// DisableIdentity - Disable an identity. Its left around for historical reporting
func (c *IdentitiesApiController) DisableIdentity(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	identityID := params["identityID"]
	result, err := c.service.DisableIdentity(identityID)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetIdentity - List identities and associates userId
func (c *IdentitiesApiController) GetIdentity(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	identityID := params["identityID"]
	result, err := c.service.GetIdentity(identityID)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// ListIdentities - List identities and associates userId
func (c *IdentitiesApiController) ListIdentities(w http.ResponseWriter, r *http.Request) {
	query := r.URL.Query()
	orgID := query.Get("orgID")
	result, err := c.service.ListIdentities(orgID)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// UpdateIdentity - Update a specific Identity
func (c *IdentitiesApiController) UpdateIdentity(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	identityID := params["identityID"]
	identity := &UpdateIdentity{}
	if err := json.NewDecoder(r.Body).Decode(&identity); err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.UpdateIdentity(identityID, *identity)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
