/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"errors"
)

// IdentitiesApiService is a service that implents the logic for the IdentitiesApiServicer
// This service should implement the business logic for every endpoint for the IdentitiesApi API. 
// Include any external packages or services that will be required by this service.
type IdentitiesApiService struct {
}

// NewIdentitiesApiService creates a default api service
func NewIdentitiesApiService() IdentitiesApiServicer {
	return &IdentitiesApiService{}
}

// DisableIdentity - Disable an identity. Its left around for historical reporting
func (s *IdentitiesApiService) DisableIdentity(identityID string) (interface{}, error) {
	// TODO - update DisableIdentity with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DisableIdentity' not implemented")
}

// GetIdentity - List identities and associates userId
func (s *IdentitiesApiService) GetIdentity(identityID string) (interface{}, error) {
	// TODO - update GetIdentity with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'GetIdentity' not implemented")
}

// ListIdentities - List identities and associates userId
func (s *IdentitiesApiService) ListIdentities(orgID string) (interface{}, error) {
	// TODO - update ListIdentities with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ListIdentities' not implemented")
}

// UpdateIdentity - Update a specific Identity
func (s *IdentitiesApiService) UpdateIdentity(identityID string, identity Identity) (interface{}, error) {
	// TODO - update UpdateIdentity with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UpdateIdentity' not implemented")
}
