/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"time"
)

type OfacSearch struct {

	// SDN EntityID of the Entity
	EntityId string `json:"entityId,omitempty"`

	// Name of the SDN entity
	SdnName string `json:"sdnName,omitempty"`

	// SDN entity type
	SdnType string `json:"sdnType,omitempty"`

	// Percentage of similarity between the Customer name and this OFAC entity
	Match float32 `json:"match,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`
}
