/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"github.com/google/uuid"
)

// CredentialsService is a service that implents the logic for the CredentialsApiServicer
// This service should implement the business logic for every endpoint for the CredentialsApi API.
// Include any external packages or services that will be required by this service.
type CredentialsService struct {
	time       TimeService
	repository CredentialRepository
}

// NewCredentialsService creates a default api service
func NewCredentialsService(time TimeService, repository CredentialRepository) *CredentialsService {
	return &CredentialsService{
		time:       time,
		repository: repository,
	}
}

// DisableCredentials - Disables a credential so it can&#39;t be used anymore to login
func (s *CredentialsService) DisableCredentials(identityID string, credentialID string) (interface{}, error) {
	cred, err := s.repository.get(credentialID)
	if err != nil {
		return nil, err
	}

	now := s.time.Now()
	callderIdentityID := "callerIdentityID" // @TODO
	cred.DisabledOn = &now
	cred.DisabledBy = &callderIdentityID

	saved, err := s.repository.update(cred)
	if err != nil {
		return nil, err
	}

	// @TODO send notification to the email to notify them?

	return saved, err
}

// ListCredentials - List the credentials this user has used.
func (s *CredentialsService) ListCredentials(identityID string) (interface{}, error) {
	return s.repository.list("tenantID", identityID)
}

func (s *CredentialsService) Login(login Login) (*Credential, error) {
	// look into the repo for any matches
	cred, err := s.repository.lookup(login.Provider, login.SubjectID)
	if err != nil {
		return nil, err
	}

	cred.LastUsedOn = s.time.Now()
	saved, err := s.repository.update(cred)
	if err != nil {
		return nil, err
	}

	// @TODO record login in a queue

	return &saved, nil
}

func (s *CredentialsService) Register(identityID string, provider string, subjectID string) (*Credential, error) {
	cred := Credential{
		CredentialID: uuid.New().String(),
		Provider:     provider,
		SubjectID:    subjectID,
		IdentityID:   identityID,
		CreatedOn:    s.time.Now(),
		LastUsedOn:   s.time.Now(),
		DisabledBy:   nil,
		DisabledOn:   nil,
	}

	saved, err := s.repository.add(cred)
	if err != nil {
		return nil, err
	}

	// @TODO record new registered credential

	// @TODO email that a new credential was registered

	return &saved, err
}
