/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"errors"
)

// IdentitiesApiService is a service that implents the logic for the IdentitiesApiServicer
// This service should implement the business logic for every endpoint for the IdentitiesApi API.
// Include any external packages or services that will be required by this service.
type IdentitiesService struct {
	repository IdentityRepository
}

// NewIdentitiesApiService creates a default api service
func NewIdentitiesService(repository IdentityRepository) IdentitiesApiServicer {
	return &IdentitiesService{
		repository: repository,
	}
}

// DisableIdentity - Disable an identity. Its left around for historical reporting
func (s *IdentitiesService) DisableIdentity(identityID string) (interface{}, error) {
	// TODO - update DisableIdentity with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'DisableIdentity' not implemented")
}

// GetIdentity - List identities and associates userId
func (s *IdentitiesService) GetIdentity(identityID string) (interface{}, error) {
	i, e := s.repository.get("1", identityID)
	if e != nil {
		return nil, errors.New("Identity not found")
	}
	return i, nil
}

// ListIdentities - List identities and associates userId
func (s *IdentitiesService) ListIdentities(orgID string) (interface{}, error) {
	// TODO - update ListIdentities with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'ListIdentities' not implemented")
}

// UpdateIdentity - Update a specific Identity
func (s *IdentitiesService) UpdateIdentity(identityID string, identity Identity) (interface{}, error) {
	// TODO - update UpdateIdentity with the required logic for this service method.
	// Add api_identities_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	return nil, errors.New("service method 'UpdateIdentity' not implemented")
}
