/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package identityserver

import (
	"errors"
)

type InvitesService struct {
	repository InvitesRepository
}

func NewInvitesService(repository InvitesRepository) InvitesApiServicer {
	return &InvitesService{
		repository: repository,
	}
}

// DeleteInvite - Delete an invite that was sent and invalidate the token.
func (s *InvitesService) DeleteInvite(inviteID string) (interface{}, error) {
	return nil, errors.New("service method 'DeleteInvite' not implemented")
}

// ListInvites - List outstanding invites
func (s *InvitesService) ListInvites(orgID string) (interface{}, error) {
	return nil, errors.New("service method 'ListInvites' not implemented")
}

// SendInvite - Send an email invite to a new user
func (s *InvitesService) SendInvite(invite Invite) (interface{}, error) {

	// add to DB

	// send email
	return nil, errors.New("service method 'SendInvite' not implemented")
}
