/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package authn

import (
	"fmt"
	"net/http"
	"strings"

	api "github.com/moov-io/identity/pkg/api"
)

// A AuthnAPIController binds http requests to an api service and writes the service results to the http response
type AuthnAPIController struct {
	service api.InternalApiServicer
}

// NewAuthnAPIController creates a default api controller
func NewAuthnAPIController(s api.InternalApiServicer) api.Router {
	return &AuthnAPIController{service: s}
}

// Routes returns all of the api route for the InternalApiController
func (c *AuthnAPIController) Routes() api.Routes {
	return api.Routes{
		{
			"Authenticated",
			strings.ToUpper("Get"),
			"/authenticated",
			c.Authenticated,
		},
		{
			"Register",
			strings.ToUpper("Post"),
			"/register",
			c.Register,
		},
	}
}

// Authenticated - Complete a login via a OIDC. Once the OIDC client service has authenticated their identity the client service will call  this endpoint to record and finish the login to get their token to use the API.  If the client service recieves a 404 they must send them to registration if its allowed per the client or check for an invite for authenticated users email before sending to registration.
func (c *AuthnAPIController) Authenticated(w http.ResponseWriter, r *http.Request) {

	session, ok := r.Context().Value("LoginSession").(*LoginSession)
	if !ok || session == nil {
		fmt.Println("Unable to find LoginSession in context")
		w.WriteHeader(500)
		return
	}

	login := api.Login{
		Provider:  session.Provider,
		SubjectID: session.SubjectID,
	}

	fmt.Println(login)

	result, err := c.service.LoginWithCredentials(login, session.State, session.IP)
	if err != nil {
		fmt.Println("Error", err.Error())

		w.WriteHeader(200)
		w.Write([]byte("Not able to exchange login token for session token"))
		return
	}

	http.SetCookie(w, result)

	w.WriteHeader(http.StatusOK)
	w.Write([]byte("You've been authenticated!"))
}

// Register - Register user based on OIDC credentials.  This is called by the OIDC client services we create to register the user with what  available information they have and obtain from the user.
func (c *AuthnAPIController) Register(w http.ResponseWriter, r *http.Request) {

	session, ok := r.Context().Value("LoginSession").(*LoginSession)
	if !ok || session == nil {
		w.WriteHeader(500)
		return
	}

	register := api.Register{
		Provider:  session.Provider,
		SubjectID: session.SubjectID,

		InviteCode: session.InviteCode,

		FirstName:  session.FirstName,
		MiddleName: session.MiddleName,
		LastName:   session.LastName,

		NickName: session.NickName,

		Suffix:    session.Suffix,
		BirthDate: session.BirthDate,

		Email: session.Email,

		Phones:    session.Phones,
		Addresses: session.Addresses,
	}

	result, err := c.service.RegisterWithCredentials(register, session.State, session.IP)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	api.EncodeJSONResponse(result, nil, w)
}
