inputSpec: /local/api/api.yml
outputDir: /local/pkg/client
generatorName: go
artifactId: "identity-client"
gitUserId: moov-io
gitRepoId: "identity"
additionalProperties:
  isGoSubmodule: true
  packageName: client
