inputSpec: /local/api/identityapi.yml
outputDir: /local/
generatorName: go-server
artifactId: identities-server
gitUserId: moov-io
gitRepoId: identity
additionalProperties:
  isGoSubmodule: true
  packageName: identityserver
  sourceFolder: pkg/server
