/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"crypto/tls"
	"database/sql"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/go-kit/kit/log"
	"github.com/gorilla/mux"
	"github.com/moov-io/base/admin"
	api "github.com/moov-io/identity/pkg/api"
	"github.com/moov-io/identity/pkg/authn"
	config "github.com/moov-io/identity/pkg/config"
	"github.com/moov-io/identity/pkg/credentials"
	"github.com/moov-io/identity/pkg/database"
	"github.com/moov-io/identity/pkg/identities"
	"github.com/moov-io/identity/pkg/invites"
	"github.com/moov-io/identity/pkg/notifications"
	"github.com/moov-io/identity/pkg/utils"
	"github.com/moov-io/identity/pkg/webkeys"
	"github.com/moov-io/identity/pkg/zerotrust"
)

var logger log.Logger

func main() {
	logger = log.NewLogfmtLogger(log.NewSyncWriter(os.Stderr))

	// Listen for application termination.
	terminationListener := newTerminationListener()

	ConfigService := config.NewConfigService(logger)

	config := &Config{}
	if err := ConfigService.Load(config); err != nil {
		return
	}

	//db setup
	db, close := initializeDatabase(logger, config.Database)
	defer close()

	TimeService := utils.NewSystemTimeService()

	FrontchannelJwks, err := webkeys.NewWebKeysService(logger, config.Authentication.Frontchannel)
	if err != nil {
		logger.Log("main", "Unable to load up up the Frontchannel JSON Web Key Set")
		return
	}

	BackchannelJwks, err := webkeys.NewWebKeysService(logger, config.Authentication.Backchannel)
	if err != nil {
		logger.Log("main", "Unable to load up the Backchannel JSON Web Key Set")
	}

	TokenService := api.NewTokenService(TimeService, FrontchannelJwks, config.Authentication.Frontchannel.Expiration)

	NotificationsService := notifications.NewNotificationsService(config.Notifications)

	IdentityRepository := identities.NewIdentityRepository(db)
	IdentitiesService := identities.NewIdentitiesService(TimeService, IdentityRepository)

	CredentialRepository := credentials.NewCredentialRepository(db)
	CredentialsService := credentials.NewCredentialsService(TimeService, CredentialRepository)

	InvitesRepository := invites.NewInvitesRepository(db)
	InvitesService := invites.NewInvitesService(config.Invites, TimeService, InvitesRepository, NotificationsService)

	InternalService := authn.NewInternalService(*CredentialsService, *IdentitiesService, TokenService)

	// internal admin server
	InternalController := authn.NewInternalAPIController(InternalService)
	adminRouter := api.NewRouter(InternalController)
	adminServer := bootAdminServer(adminRouter, terminationListener, logger, config.Admin)
	defer adminServer.Shutdown()

	// public server

	// auth middleware for the back channel
	authMiddleware, err := zerotrust.NewJWTMiddleware(BackchannelJwks)
	if err != nil {
		logger.Log("main", fmt.Sprintf("Can't startup the front channel middleware - %s", err))
		return
	}

	// debug api
	WhoAmIController := api.NewWhoAmIController()

	IdentitiesController := identities.NewIdentitiesApiController(IdentitiesService)
	CredentialsController := credentials.NewCredentialsApiController(CredentialsService)
	InvitesController := invites.NewInvitesController(InvitesService)
	publicRouter := api.NewRouter(IdentitiesController, CredentialsController, InvitesController, WhoAmIController)
	authedRouter := authMiddleware.Handler(publicRouter)

	_, shutdownServer := bootPublicServer(authedRouter, terminationListener, logger, config.HTTP)
	defer shutdownServer()

	awaitTermination(terminationListener)
}

func newTerminationListener() chan error {
	errs := make(chan error)
	go func() {
		c := make(chan os.Signal, 1)
		signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)
		errs <- fmt.Errorf("%s", <-c)
	}()

	return errs
}

func awaitTermination(terminationListener chan error) {
	if err := <-terminationListener; err != nil {
		logger.Log("exit", err)
	}
}

func bootAdminServer(adminRouter *mux.Router, errs chan<- error, logger log.Logger, config HTTPConfig) *admin.Server {
	adminServer := admin.NewServer(config.Bind.Address)

	adminServer.AddHandler("/", adminRouter.ServeHTTP)

	go func() {
		logger.Log("admin", fmt.Sprintf("listening on %s", adminServer.BindAddr()))
		if err := adminServer.Listen(); err != nil {
			err = fmt.Errorf("problem starting admin http: %v", err)
			logger.Log("admin", err)
			errs <- err // send err to shutdown channel
		}
	}()

	return adminServer
}

func bootPublicServer(routes http.Handler, errs chan<- error, logger log.Logger, config HTTPConfig) (*http.Server, func()) {

	// Create main HTTP server
	serve := &http.Server{
		Addr:    config.Bind.Address,
		Handler: routes,
		TLSConfig: &tls.Config{
			InsecureSkipVerify:       false,
			PreferServerCipherSuites: true,
			MinVersion:               tls.VersionTLS12,
		},
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
		IdleTimeout:  60 * time.Second,
	}

	// Start main HTTP server
	go func() {
		logger.Log("http", fmt.Sprintf("listening on %s", config.Bind.Address))
		if err := serve.ListenAndServe(); err != nil {
			err = fmt.Errorf("problem starting http: %v", err)
			logger.Log("http", err)
			errs <- err // send err to shutdown channel
		}
	}()

	shutdownServer := func() {
		if err := serve.Shutdown(context.TODO()); err != nil {
			logger.Log("exit", err)
		}
	}

	return serve, shutdownServer
}

func initializeDatabase(logger log.Logger, config database.DatabaseConfig) (*sql.DB, func()) {
	ctx, cancelFunc := context.WithCancel(context.Background())

	// migrate database
	db, err := database.New(ctx, logger, config)
	if err != nil {
		panic(fmt.Sprintf("error creating database: %v", err))
	}

	shutdown := func() {
		cancelFunc()
		if err := db.Close(); err != nil {
			logger.Log("exit", err)
		}
	}

	if err := database.RunMigrations(db); err != nil {
		panic(fmt.Sprintf("Error running migrations: %s", err))
	}

	return db, shutdown
}
