servers:
  public:
    bind:
      address: ":8200"
  private:
    bind:
      address: ":8201"
  admin:
    bind:
      address: ":8202"
database:
  databaseName: "identity"
  sqllite:
    path: ./data/identity.db
invites:
  expiration: 48h
  sendToURL: https://api.moov.io
session:
  expiration: 1h
keys:
  authn-public:
    file:
      path: ./configs/jwk-sig-pub.json
  gateway-public:
    file:
      path: ./configs/jwk-sig-pub.json
  session-private:
    file:
      path: ./configs/jwk-sig-priv.json