Identity:
  Servers:
    Public:
      Bind:
        Address: ":8200"
    Admin:
      Bind:
        Address: ":8201"
  Database:
    DatabaseName: "identity"
    SQLLite:
      Path: ":memory:"
  Services:
    Authn: http://authn:8202
  Invites:
    Expiration: 48h
    SendToHost: https://api.moov.io 
    SendToPath: /authentication/tenants/{{.TenantID}}
  Notifications:
    Mock:
      From: noreply@moov.io
  Gateway:
    # Examples of how to set up this config.
    # keys:
    #   http:
    #    urls:
    #    - http://oathkeeper:4456/.well-known/jwks.json
    #   file:
    #     paths: 
    #     - ./configs/gateway-jwks-sig-pub.json

  Authentication:
    LandingUrl: "/whoami"
    # keys:
    #   http:
    #    urls:
    #    - http://authn:8202/.well-known/jwks.json
    #   file:
    #     paths: 
    #     - ./configs/authn-jwks-sig-pub.json
  Session:
    Expiration: 1h
    EnablePutSession: false
    # keys:
    #   paths:
    #   - ./configs/identity-jwks-sig-pub.json
    #   - ./configs/identity-jwks-sig-priv.json