servers:
  public:
    bind:
      address: ":8200"
  admin:
    bind:
      address: ":8202"
database:
  databaseName: "identity"
  sqllite:
    path: ./data/identity.db
invites:
  expiration: 48h
  sendToURL: https://api.moov.io
session:
  expiration: 1h
keys:
  authnPublic:
    file:
      path: ./configs/jwk-sig-pub.json
  gatewayPublic:
    file:
      path: ./configs/jwk-sig-pub.json
  sessionPrivate:
    file:
      path: ./configs/jwk-sig-priv.json