servers:
  public:
    bind:
      address: ":8200"
  admin:
    bind:
      address: ":8201"
database:
  databaseName: "identity"
  sqllite:
    path: ":memory:"
invites:
  expiration: 48h
  sendToURL: https://api.moov.io
notifications:
  Mock:
    from: noreply@moov.io
session:
  expiration: 1h
  landingUrl: "/whoami"
keys:
  # Examples of how to set up this config.
  # authnPublic:
  #   http:
  #    url: http://authn:8202/.well-known/jwks.json
  #   file:
  #     path: ./configs/authn-jwks-sig-pub.json
  # gatewayPublic:
  #   http:
  #    url: http://oathkeeper:4456/.well-known/jwks.json
  #   file:
  #     path: ./configs/gateway-jwks-sig-pub.json
  # sessionPublic:
  #   file:
  #     path: ./configs/identity-jwks-sig-pub.json
  # sessionPrivate:
  #   file:
  #     path: ./configs/identity-jwks-sig-priv.json