http:
  bind:
    address: ":8301"
admin:
  bind:
    address: ":8302"
database:
  sqllite:
    path: bin/identity.db
authentication:
  frontchannel:
    expiration: 1h
    file:
      path: ./configs/jwk-sig-priv.json
  backchannel:
    file:
      path: ./configs/jwk-sig-pub.json
invites:
  expiration: 2d