servers:
  public:
    bind:
      address: ":8200"
  admin:
    bind:
      address: ":8201"
database:
  databaseName: "identity"
  sqllite:
    path: ":memory:"
invites:
  expiration: 48h
  sendToURL: https://api.moov.io/authentication/{{.TenantID}}/
notifications:
  Mock:
    from: noreply@moov.io
gateway:
  # Examples of how to set up this config.
  # keys:
  #   http:
  #    urls:
  #    - http://oathkeeper:4456/.well-known/jwks.json
  #   file:
  #     paths: 
  #     - ./configs/gateway-jwks-sig-pub.json

authentication:
  landingUrl: "/whoami"
  # keys:
  #   http:
  #    urls:
  #    - http://authn:8202/.well-known/jwks.json
  #   file:
  #     paths: 
  #     - ./configs/authn-jwks-sig-pub.json
session:
  expiration: 1h
  # keys:
  #   paths:
  #   - ./configs/identity-jwks-sig-pub.json
  #   - ./configs/identity-jwks-sig-priv.json
