/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// RegisterErrors Request to register a user in the system
type RegisterErrors struct {
	// Descriptive reason for failing validation
	FirstName *string `json:"firstName,omitempty"`
	// Descriptive reason for failing validation
	MiddleName *string `json:"middleName,omitempty"`
	// Descriptive reason for failing validation
	LastName *string `json:"lastName,omitempty"`
	// Descriptive reason for failing validation
	NickName *string `json:"nickName,omitempty"`
	// Descriptive reason for failing validation
	Suffix *string `json:"suffix,omitempty"`
	// Descriptive reason for failing validation
	BirthDate *string `json:"birthDate,omitempty"`
	// Descriptive reason for failing validation
	Email *string `json:"email,omitempty"`
	Phones []RegisterPhoneErrors `json:"phones,omitempty"`
	Addresses []RegisterAddressErrors `json:"addresses,omitempty"`
}
