/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// UpdateAddress Address of the Identity
type UpdateAddress struct {
	// UUID v4
	AddressID  string  `json:"addressID,omitempty"`
	Type       string  `json:"type,omitempty"`
	Address1   string  `json:"address1,omitempty"`
	Address2   *string `json:"address2,omitempty"`
	City       string  `json:"city,omitempty"`
	PostalCode string  `json:"postalCode,omitempty"`
	State      string  `json:"state,omitempty"`
	Country    string  `json:"country,omitempty"`
	Validated  bool    `json:"validated,omitempty"`
}
