/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// Credential Description of a successful OpenID connect credential
type Credential struct {
	// UUID v4
	CredentialID string `json:"credentialID,omitempty"`
	// UUID v4
	IdentityID string `json:"identityID,omitempty"`
	// UUID v4
	TenantID   string     `json:"tenantID,omitempty"`
	CreatedOn  time.Time  `json:"createdOn,omitempty"`
	LastUsedOn time.Time  `json:"lastUsedOn,omitempty"`
	DisabledOn *time.Time `json:"disabledOn,omitempty"`
	// UUID v4
	DisabledBy *string `json:"disabledBy,omitempty"`
}
