/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// SessionDetails User has logged in and is being given a token to proof identity
type SessionDetails struct {
	// UUID v4
	CredentialID string `json:"credentialID,omitempty"`
	// UUID v4
	TenantID string `json:"tenantID,omitempty"`
	// UUID v4
	IdentityID string  `json:"identityID,omitempty"`
	FirstName  string  `json:"firstName,omitempty"`
	LastName   string  `json:"lastName,omitempty"`
	NickName   *string `json:"nickName,omitempty"`
	ImageUrl   *string `json:"imageUrl,omitempty"`
	// Expires in seconds
	ExpiresIn int64 `json:"expiresIn,omitempty"`
}
