/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform. 
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// RegisterPhoneErrors Phone number
type RegisterPhoneErrors struct {
	// Descriptive reason for failing validation
	Number *string `json:"number,omitempty"`
	// Descriptive reason for failing validation
	Type *string `json:"type,omitempty"`
}
