/*
 * Moov Identity API
 *
 * Handles all identities for tracking the users of the Moov platform.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// ChangeSessionDetails User has logged in and is being given a token to proof identity
type ChangeSessionDetails struct {
	// UUID v4
	TenantID *string `json:"tenantID,omitempty"`
}
